/*
 * Copyright 2017 root.
 * Todos os direitos reservados.
 *
 * É permitida a redistribuição e o uso em formulários originais e binários, com ou
 * sem modificação, desde que sejam cumpridas as seguintes condições:
 *
 *  * Redistribuições do código-fonte devem manter o aviso de direitos autorais acima, 
 *   esta lista de condições e a seguinte isenção.
 *
 *  * As redistribuições em formato binário devem reproduzir o aviso de copyright acima,
 *   esta lista de condições ea seguinte isenção de responsabilidade na documentação
 *   e / ou outros materiais fornecidos com a distribuição.
 *
 *  * Nem o nome do Expression project.organization!organization is undefined on line 17, column 36 in Templates/Licenses/license-bsd_3-pt_br.txt. nem os nomes dos seus contribuidores 
 *   podem ser utilizados para endossar ou promover produtos derivados deste software sem
 *   autorização prévia específica por escrito.
 *
 * ESTE SOFTWARE É FORNECIDO PELOS DETENTORES DE COPYRIGHT E COLABORADORES "NO ESTADO EM QUE SE ENCONTRAM"
 * E QUAISQUER GARANTIAS EXPRESSAS OU IMPLÍCITAS, INCLUINDO, MAS NÃO SE LIMITANDO A,
 * GARANTIAS IMPLÍCITAS DE COMERCIABILIDADE E ADEQUAÇÃO A UM PROPÓSITO ESPECÍFICO.
 * EM NENHUMA CIRCUNSTÂNCIA O PROPRIETÁRIO OU OS CONTRIBUIDORES SERÃO
 * RESPONSÁVEIS POR QUAISQUER DANOS DIRETOS, INDIRETOS, INCIDENTAIS, ESPECIAIS, EXEMPLARES OU
 * CONSEQÜENCIAIS (INCLUINDO, MAS NÃO SE LIMITANDO À, AQUISIÇÃO DE
 * BENS OU SERVIÇOS SUBSTITUTOS, PERDA DE USO, DADOS OU LUCROS; OU INTERRUPÇÃO DE NEGÓCIOS),
 * QUALQUER CAUSA E QUALQUER TEORIA DE RESPONSABILIDADE,  
 * SEJA POR CONTRATO, RESPONSABILIDADE ESTRITA OU DANO (INCLUINDO NEGLIGÊNCIA OU QUALQUER OUTRA)
 * DECORRENTE DE QUALQUER FORMA FORA DO USO DESTE SOFTWARE, MESMO SE AVISADO DA 
 * POSSIBILIDADE DE TAIS DANOS.
 */
package view;

import dao.ColetaDAO;
import dao.TweetDAO;
import engines.Graficos;
import entidade.Coleta;
import entidade.Tweet;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import tablemodel.TableModelColeta;
import tablemodel.TableModelTweet;

/**
 *
 * @author root
 */
public class ColetasGUI extends javax.swing.JDialog {

    private TableModelColeta modelColeta;
    private TableModelTweet modelTweet;
    private ColetaDAO colDAO;
    private List<Coleta> coletas;
    private TweetDAO tweetDAO;
    private List<Tweet> tweets;
    private Graficos grafico;

    /**
     * Creates new form ColetasGUI
     */
    public ColetasGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        modelColeta = new TableModelColeta();
        modelTweet = new TableModelTweet();
        initComponents();
        tweetDAO = new TweetDAO();
        colDAO = new ColetaDAO();
        coletas = colDAO.listar();
        colDAO.closeConnection();
        preencherColetas(coletas);
        grafico = new Graficos();
    }

    private void preencherColetas(List<Coleta> list) {
        if (list != null && list.size() > 0) {
            for (Coleta c : list) {
                modelColeta.addColeta(c);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbTotal = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbOriginais = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbRetweets = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnOriginal = new javax.swing.JButton();
        btnRetweet = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableTweets = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableColeta = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel3.setLayout(new java.awt.GridLayout(3, 2));

        jLabel1.setText("Quantidade total de tweets:");
        jPanel3.add(jLabel1);

        lbTotal.setForeground(new java.awt.Color(0, 0, 204));
        lbTotal.setText("0");
        jPanel3.add(lbTotal);

        jLabel2.setText("Quantidade de tweets originais:");
        jPanel3.add(jLabel2);

        lbOriginais.setForeground(new java.awt.Color(0, 0, 204));
        lbOriginais.setText("0");
        jPanel3.add(lbOriginais);

        jLabel3.setText("Quantidade de retweets:");
        jPanel3.add(jLabel3);

        lbRetweets.setForeground(new java.awt.Color(0, 0, 204));
        lbRetweets.setText("0");
        jPanel3.add(lbRetweets);

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        jLabel4.setText("Coletas:");

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        btnOriginal.setText("Originais");
        btnOriginal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOriginalActionPerformed(evt);
            }
        });
        jPanel5.add(btnOriginal);

        btnRetweet.setText("Retweets");
        btnRetweet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetweetActionPerformed(evt);
            }
        });
        jPanel5.add(btnRetweet);

        jButton4.setText("Exportar");
        jPanel5.add(jButton4);

        jButton5.setText("Gráficos");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton5);

        tableTweets.setModel(modelTweet);
        jScrollPane3.setViewportView(tableTweets);

        tableColeta.setModel(modelColeta);
        tableColeta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableColetaMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tableColeta);

        jLabel5.setText("Tweets:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(11, 11, 11))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableColetaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableColetaMouseClicked
        exibirTweets();
    }//GEN-LAST:event_tableColetaMouseClicked

    private void exibirTweets() {
        modelTweet.limparTabela();
        Coleta coleta = (Coleta) modelColeta.getSelecionado(tableColeta.getSelectedRow());
        if (coleta != null) {
            tweets = tweetDAO.getTweets(coleta);
            if (tweets != null && tweets.size() > 0) {
                for (Tweet t : tweets) {
                    modelTweet.addTweet(t);
                }
            }
            calcular();
            tweets.clear();
        }
    }

    private void calcular() {
        int qtdTotal = tweets.size();
        int qtdOriginais = 0;
        int qtdRetweets = 0;
        int qtdGeo = 0;

        for (Tweet t : tweets) {
            if (t.getRetweet() == 0) {
                qtdOriginais++;
            }
            if (t.getLatitude() != 0.0 && t.getLongitude() != 0) {
                qtdGeo++;
            }
        }
        qtdRetweets = qtdTotal - qtdOriginais;

        lbTotal.setText(String.valueOf(qtdTotal));
        lbOriginais.setText(String.valueOf(qtdOriginais));
        lbRetweets.setText(String.valueOf(qtdRetweets));
    }

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (tweetDAO != null) {
            tweetDAO.closeConnection();
        }
    }//GEN-LAST:event_formWindowClosing

    private void btnOriginalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOriginalActionPerformed
        exibirTweets(0);
    }//GEN-LAST:event_btnOriginalActionPerformed

    private void btnRetweetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetweetActionPerformed
        exibirTweets(1);
    }//GEN-LAST:event_btnRetweetActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        grafico.addValue("originais", Double.parseDouble(lbOriginais.getText()));
        grafico.addValue("retweets", Double.parseDouble(lbRetweets.getText()));
        grafico.criarDataset();
        JPanel graf = grafico.getGrafico();
        Grafico gui = new Grafico(graf);
        graf.setVisible(true);
        gui.setLocationRelativeTo(this);
        gui.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void exibirTweets(int opcao){
        modelTweet.limparTabela();
        Coleta coleta = (Coleta) modelColeta.getSelecionado(tableColeta.getSelectedRow());
        if (coleta != null) {
            tweets = tweetDAO.getTweets(coleta);
            if (tweets != null && tweets.size() > 0) {
                for (Tweet t : tweets) {
                    if (t.getRetweet() == opcao) {
                        modelTweet.addTweet(t);
                    }
                }
            }
            tweets.clear();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ColetasGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ColetasGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ColetasGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ColetasGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ColetasGUI dialog = new ColetasGUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOriginal;
    private javax.swing.JButton btnRetweet;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbOriginais;
    private javax.swing.JLabel lbRetweets;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JTable tableColeta;
    private javax.swing.JTable tableTweets;
    // End of variables declaration//GEN-END:variables
}
