/*
 * Copyright 2016 root.
 * All rights reserved.
 *
 * É permitida a redistribuição e o uso em formulários originais e binários, com ou
 * sem modificação, desde que sejam cumpridas as seguintes condições:
 *
 *  * Redistribuições do código-fonte devem manter o aviso de direitos autorais acima, 
 *   esta lista de condições e a seguinte isenção.
 *
 *  * As redistribuições em formato binário devem reproduzir o aviso de copyright acima,
 *   esta lista de condições ea seguinte isenção de responsabilidade na documentação
 *   e / ou outros materiais fornecidos com a distribuição.
 *
 *  * Nem o nome do Expression project.organization is undefined on line 17, column 36 in Templates/Licenses/license-bsd_3-pt_br.txt. nem os nomes dos seus contribuidores 
 *   podem ser utilizados para endossar ou promover produtos derivados deste software sem
 *   autorização prévia específica por escrito.
 *
 * ESTE SOFTWARE É FORNECIDO PELOS DETENTORES DE COPYRIGHT E COLABORADORES "NO ESTADO EM QUE SE ENCONTRAM"
 * E QUAISQUER GARANTIAS EXPRESSAS OU IMPLÍCITAS, INCLUINDO, MAS NÃO SE LIMITANDO A,
 * GARANTIAS IMPLÍCITAS DE COMERCIABILIDADE E ADEQUAÇÃO A UM PROPÓSITO ESPECÍFICO.
 * EM NENHUMA CIRCUNSTÂNCIA O PROPRIETÁRIO OU OS CONTRIBUIDORES SERÃO
 * RESPONSÁVEIS POR QUAISQUER DANOS DIRETOS, INDIRETOS, INCIDENTAIS, ESPECIAIS, EXEMPLARES OU
 * CONSEQÜENCIAIS (INCLUINDO, MAS NÃO SE LIMITANDO À, AQUISIÇÃO DE
 * BENS OU SERVIÇOS SUBSTITUTOS, PERDA DE USO, DADOS OU LUCROS; OU INTERRUPÇÃO DE NEGÓCIOS),
 * QUALQUER CAUSA E QUALQUER TEORIA DE RESPONSABILIDADE,  
 * SEJA POR CONTRATO, RESPONSABILIDADE ESTRITA OU DANO (INCLUINDO NEGLIGÊNCIA OU QUALQUER OUTRA)
 * DECORRENTE DE QUALQUER FORMA FORA DO USO DESTE SOFTWARE, MESMO SE AVISADO DA 
 * POSSIBILIDADE DE TAIS DANOS.
 */
package view;

import control.MapsController;
import java.awt.Color;

/**
 *
 * @author root
 */
public class MapsGUI extends javax.swing.JDialog {

    

    /**
     * Creates new form MapemaentoGUI
     *
     * @param parent
     * @param modal
     */
    public MapsGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
        MapsController.inicializar();

    }

    public MapsGUI() {
        initComponents();
        init();
        MapsController.inicializar();
        MapsController.mapaAutomatico();
    }

    private void init() {
        buttonGroup.add(rdArquivoExt);
        buttonGroup.add(rdProcessoAtual);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        painelMapa = new javax.swing.JPanel();
        painelExibicao = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        campoDir = new javax.swing.JTextField();
        btnAbrir = new javax.swing.JButton();
        btnGerarMapa = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        primeiro = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        segundo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        terceiro = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        quarto = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        quinto = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        rdProcessoAtual = new javax.swing.JRadioButton();
        rdArquivoExt = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mapeamento de incidências");
        setResizable(false);

        painelMapa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        painelMapa.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Locais com maior incidência");

        campoDir.setEditable(false);
        campoDir.setEnabled(false);

        btnAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Folder-Open-icon.png"))); // NOI18N
        btnAbrir.setEnabled(false);
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirActionPerformed(evt);
            }
        });

        btnGerarMapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/maps-icon.png"))); // NOI18N
        btnGerarMapa.setText("Mapa");
        btnGerarMapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarMapaActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridLayout(5, 2));

        jLabel2.setText("1º:");
        jPanel1.add(jLabel2);

        primeiro.setText("...");
        primeiro.setToolTipText("Exibir o mapa deste local");
        primeiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primeiroMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                primeiroMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                primeiroMouseEntered(evt);
            }
        });
        jPanel1.add(primeiro);

        jLabel3.setText("2º:");
        jPanel1.add(jLabel3);

        segundo.setText("...");
        segundo.setToolTipText("Exibir o mapa deste local");
        segundo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                segundoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                segundoMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                segundoMouseEntered(evt);
            }
        });
        jPanel1.add(segundo);

        jLabel4.setText("3º:");
        jPanel1.add(jLabel4);

        terceiro.setText("...");
        terceiro.setToolTipText("Exibir o mapa deste local");
        terceiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                terceiroMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                terceiroMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                terceiroMouseEntered(evt);
            }
        });
        jPanel1.add(terceiro);

        jLabel5.setText("4º:");
        jPanel1.add(jLabel5);

        quarto.setText("...");
        quarto.setToolTipText("Exibir o mapa deste local");
        quarto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quartoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                quartoMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                quartoMouseEntered(evt);
            }
        });
        jPanel1.add(quarto);

        jLabel6.setText("5º:");
        jPanel1.add(jLabel6);

        quinto.setText("...");
        quinto.setToolTipText("Exibir o mapa deste local");
        quinto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quintoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                quintoMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                quintoMouseEntered(evt);
            }
        });
        jPanel1.add(quinto);

        javax.swing.GroupLayout painelExibicaoLayout = new javax.swing.GroupLayout(painelExibicao);
        painelExibicao.setLayout(painelExibicaoLayout);
        painelExibicaoLayout.setHorizontalGroup(
            painelExibicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelExibicaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelExibicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(campoDir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGerarMapa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAbrir, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        painelExibicaoLayout.setVerticalGroup(
            painelExibicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelExibicaoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(campoDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAbrir)
                .addGap(30, 30, 30)
                .addComponent(btnGerarMapa)
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Fonte de Dados"));
        jPanel2.setLayout(new java.awt.GridLayout(1, 2));

        rdProcessoAtual.setSelected(true);
        rdProcessoAtual.setText("Processo atual");
        rdProcessoAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdProcessoAtualActionPerformed(evt);
            }
        });
        jPanel2.add(rdProcessoAtual);

        rdArquivoExt.setText("Arquivo Externo");
        rdArquivoExt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdArquivoExtActionPerformed(evt);
            }
        });
        jPanel2.add(rdArquivoExt);

        jPanel3.setBackground(new java.awt.Color(64, 64, 64));

        lbTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Georeferencia.png"))); // NOI18N
        jPanel3.add(lbTitulo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelMapa, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelExibicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1031, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painelMapa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(painelExibicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdProcessoAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdProcessoAtualActionPerformed
        MapsController.limparInformacoes();
    }//GEN-LAST:event_rdProcessoAtualActionPerformed

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed
        MapsController.getEntrada();
    }//GEN-LAST:event_btnAbrirActionPerformed

    private void btnGerarMapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarMapaActionPerformed
        MapsController.visualizarMapa();
    }//GEN-LAST:event_btnGerarMapaActionPerformed

    private void primeiroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primeiroMouseEntered
        primeiro.setForeground(Color.BLUE);
    }//GEN-LAST:event_primeiroMouseEntered

    private void primeiroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primeiroMouseExited
        primeiro.setForeground(Color.BLACK);
    }//GEN-LAST:event_primeiroMouseExited

    private void segundoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_segundoMouseEntered
        segundo.setForeground(Color.BLUE);
    }//GEN-LAST:event_segundoMouseEntered

    private void segundoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_segundoMouseExited
        segundo.setForeground(Color.BLACK);
    }//GEN-LAST:event_segundoMouseExited

    private void terceiroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_terceiroMouseEntered
        terceiro.setForeground(Color.BLUE);
    }//GEN-LAST:event_terceiroMouseEntered

    private void terceiroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_terceiroMouseExited
        terceiro.setForeground(Color.BLACK);
    }//GEN-LAST:event_terceiroMouseExited

    private void quartoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quartoMouseEntered
        quarto.setForeground(Color.BLUE);
    }//GEN-LAST:event_quartoMouseEntered

    private void quartoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quartoMouseExited
        quarto.setForeground(Color.BLACK);
    }//GEN-LAST:event_quartoMouseExited

    private void quintoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quintoMouseEntered
        quinto.setForeground(Color.BLUE);
    }//GEN-LAST:event_quintoMouseEntered

    private void quintoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quintoMouseExited
        quinto.setForeground(Color.BLACK);
    }//GEN-LAST:event_quintoMouseExited

    private void primeiroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primeiroMouseClicked
        MapsController.exibirMapa(0);        
    }//GEN-LAST:event_primeiroMouseClicked

    private void segundoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_segundoMouseClicked
        MapsController.exibirMapa(1);  
    }//GEN-LAST:event_segundoMouseClicked

    private void terceiroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_terceiroMouseClicked
        MapsController.exibirMapa(2);  
    }//GEN-LAST:event_terceiroMouseClicked

    private void quartoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quartoMouseClicked
        MapsController.exibirMapa(3);  
    }//GEN-LAST:event_quartoMouseClicked

    private void quintoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quintoMouseClicked
        MapsController.exibirMapa(4);  
    }//GEN-LAST:event_quintoMouseClicked

    private void rdArquivoExtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdArquivoExtActionPerformed
        MapsController.limparInformacoes();
        MapsController.verificarSeletores();
    }//GEN-LAST:event_rdArquivoExtActionPerformed

    

    

    /**
     * @param args the command line arguments
     * @param block
     */
    public static void main(String args[], String block) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MapsGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MapsGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MapsGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MapsGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            MapsGUI dialog = new MapsGUI(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnGerarMapa;
    private javax.swing.ButtonGroup buttonGroup;
    public static javax.swing.JTextField campoDir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JPanel painelExibicao;
    public static javax.swing.JPanel painelMapa;
    public static javax.swing.JLabel primeiro;
    public static javax.swing.JLabel quarto;
    public static javax.swing.JLabel quinto;
    public static javax.swing.JRadioButton rdArquivoExt;
    public static javax.swing.JRadioButton rdProcessoAtual;
    public static javax.swing.JLabel segundo;
    public static javax.swing.JLabel terceiro;
    // End of variables declaration//GEN-END:variables
}
