/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.WatsonController;
import javax.swing.JOptionPane;

/**
 *
 * @author root
 */
public class WatsonGUI extends javax.swing.JDialog {


    /**
     * Creates new form CleanerGUI
     */
    public WatsonGUI() {
        initComponents();
        buttonGroup.add(rdbUnico);
        buttonGroup.add(rdbMultiplos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        lbTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        campoEntrada = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        campoSaida = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        painelMestre = new javax.swing.JTabbedPane();
        painelInterno = new javax.swing.JPanel();
        painelOpcoes = new javax.swing.JPanel();
        chkAcent = new javax.swing.JCheckBox();
        chkRemoveLink = new javax.swing.JCheckBox();
        chkRT = new javax.swing.JCheckBox();
        painelBotao = new javax.swing.JPanel();
        btnProcessar = new javax.swing.JButton();
        painelProgresso = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        progresso = new javax.swing.JProgressBar();
        painelInternoDesm = new javax.swing.JPanel();
        painelMenu = new javax.swing.JPanel();
        painelOpcoes2 = new javax.swing.JPanel();
        chkAcent2 = new javax.swing.JCheckBox();
        chkRemoveRT2 = new javax.swing.JCheckBox();
        chkRemoveLink2 = new javax.swing.JCheckBox();
        painelBotao1 = new javax.swing.JPanel();
        botaoDesmembrar = new javax.swing.JButton();
        painelProgresso1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        progressDesm = new javax.swing.JProgressBar();
        painelSeparacao = new javax.swing.JPanel();
        rdbMultiplos = new javax.swing.JRadioButton();
        rdbUnico = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        qtdArquivos = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        painelMenu1 = new javax.swing.JPanel();
        painelOpcoes3 = new javax.swing.JPanel();
        chkAcentCond = new javax.swing.JCheckBox();
        chkRemoveRTCond = new javax.swing.JCheckBox();
        chkRemoveLinkCond = new javax.swing.JCheckBox();
        painelBotao2 = new javax.swing.JPanel();
        botaoCondensar = new javax.swing.JButton();
        painelProgresso2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        barraProgressoCond = new javax.swing.JProgressBar();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(64, 64, 64));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15);
        flowLayout1.setAlignOnBaseline(true);
        jPanel1.setLayout(flowLayout1);

        lbTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/WatsonToolkit.png"))); // NOI18N
        jPanel1.add(lbTitle);

        jLabel1.setText("Entrada:");

        campoEntrada.setEditable(false);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Folder-Open-icon.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Saida:");

        campoSaida.setEditable(false);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/save.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        painelOpcoes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        painelOpcoes.setLayout(new java.awt.GridLayout(3, 2));

        chkAcent.setText("Remover Acentuações");
        painelOpcoes.add(chkAcent);

        chkRemoveLink.setText("Remover Links");
        chkRemoveLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkRemoveLinkActionPerformed(evt);
            }
        });
        painelOpcoes.add(chkRemoveLink);

        chkRT.setText("Remover Retweets");
        painelOpcoes.add(chkRT);

        painelBotao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnProcessar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/converter.png"))); // NOI18N
        btnProcessar.setText("Converter");
        btnProcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessarActionPerformed(evt);
            }
        });
        painelBotao.add(btnProcessar);

        painelProgresso.setLayout(new java.awt.GridLayout(2, 0));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Progresso");
        painelProgresso.add(jLabel3);

        progresso.setStringPainted(true);
        painelProgresso.add(progresso);

        javax.swing.GroupLayout painelInternoLayout = new javax.swing.GroupLayout(painelInterno);
        painelInterno.setLayout(painelInternoLayout);
        painelInternoLayout.setHorizontalGroup(
            painelInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelInternoLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(painelInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painelProgresso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelBotao, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(painelInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelInternoLayout.createSequentialGroup()
                    .addContainerGap(35, Short.MAX_VALUE)
                    .addComponent(painelOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(36, 36, 36)))
        );
        painelInternoLayout.setVerticalGroup(
            painelInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelInternoLayout.createSequentialGroup()
                .addContainerGap(256, Short.MAX_VALUE)
                .addComponent(painelBotao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(painelProgresso, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(painelInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painelInternoLayout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addComponent(painelOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(209, Short.MAX_VALUE)))
        );

        painelMestre.addTab("Conversor", painelInterno);

        painelMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        painelOpcoes2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        painelOpcoes2.setLayout(new java.awt.GridLayout(3, 2));

        chkAcent2.setText("Remover Acentuações");
        painelOpcoes2.add(chkAcent2);

        chkRemoveRT2.setText("Remover Retweets");
        painelOpcoes2.add(chkRemoveRT2);

        chkRemoveLink2.setText("Remover Links");
        painelOpcoes2.add(chkRemoveLink2);

        painelBotao1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        botaoDesmembrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fragment.png"))); // NOI18N
        botaoDesmembrar.setText("Fragmentar");
        botaoDesmembrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDesmembrarActionPerformed(evt);
            }
        });
        painelBotao1.add(botaoDesmembrar);

        painelProgresso1.setLayout(new java.awt.GridLayout(2, 0));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Progresso");
        painelProgresso1.add(jLabel4);

        progressDesm.setName(""); // NOI18N
        progressDesm.setStringPainted(true);
        painelProgresso1.add(progressDesm);

        painelSeparacao.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Separar em"));
        painelSeparacao.setLayout(new java.awt.GridLayout(1, 0));

        rdbMultiplos.setSelected(true);
        rdbMultiplos.setText("Em diretórios");
        rdbMultiplos.setToolTipText("Separa os arquivos em cópias idênticas dos diretórios de origem!");
        painelSeparacao.add(rdbMultiplos);

        rdbUnico.setText("Diretório único");
        rdbUnico.setToolTipText("Separa os arquivos em um único diretório!");
        painelSeparacao.add(rdbUnico);

        javax.swing.GroupLayout painelMenuLayout = new javax.swing.GroupLayout(painelMenu);
        painelMenu.setLayout(painelMenuLayout);
        painelMenuLayout.setHorizontalGroup(
            painelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelBotao1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelProgresso1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelSeparacao, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(painelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painelMenuLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(painelOpcoes2, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        painelMenuLayout.setVerticalGroup(
            painelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelMenuLayout.createSequentialGroup()
                .addComponent(painelSeparacao, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addComponent(painelBotao1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(painelProgresso1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(painelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painelMenuLayout.createSequentialGroup()
                    .addGap(74, 74, 74)
                    .addComponent(painelOpcoes2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(175, Short.MAX_VALUE)))
        );

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Quantidade de arquivos gerados:");

        qtdArquivos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        qtdArquivos.setText("0");

        javax.swing.GroupLayout painelInternoDesmLayout = new javax.swing.GroupLayout(painelInternoDesm);
        painelInternoDesm.setLayout(painelInternoDesmLayout);
        painelInternoDesmLayout.setHorizontalGroup(
            painelInternoDesmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelInternoDesmLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel8)
                .addGap(27, 27, 27)
                .addComponent(qtdArquivos, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(221, Short.MAX_VALUE))
            .addGroup(painelInternoDesmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelInternoDesmLayout.createSequentialGroup()
                    .addContainerGap(15, Short.MAX_VALUE)
                    .addComponent(painelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(15, Short.MAX_VALUE)))
        );
        painelInternoDesmLayout.setVerticalGroup(
            painelInternoDesmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelInternoDesmLayout.createSequentialGroup()
                .addContainerGap(410, Short.MAX_VALUE)
                .addGroup(painelInternoDesmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(qtdArquivos))
                .addContainerGap())
            .addGroup(painelInternoDesmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painelInternoDesmLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(painelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(39, Short.MAX_VALUE)))
        );

        painelMestre.addTab("Fragmentador", painelInternoDesm);

        painelMenu1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        painelOpcoes3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        painelOpcoes3.setLayout(new java.awt.GridLayout(3, 2));

        chkAcentCond.setText("Remover Acentuações");
        painelOpcoes3.add(chkAcentCond);

        chkRemoveRTCond.setText("Remover Retweets");
        painelOpcoes3.add(chkRemoveRTCond);

        chkRemoveLinkCond.setText("Remover Links");
        painelOpcoes3.add(chkRemoveLinkCond);

        painelBotao2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        botaoCondensar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/merge.png"))); // NOI18N
        botaoCondensar.setText("Mesclar");
        botaoCondensar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCondensarActionPerformed(evt);
            }
        });
        painelBotao2.add(botaoCondensar);

        painelProgresso2.setLayout(new java.awt.GridLayout(2, 0));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Progresso");
        painelProgresso2.add(jLabel9);

        barraProgressoCond.setName(""); // NOI18N
        barraProgressoCond.setStringPainted(true);
        painelProgresso2.add(barraProgressoCond);

        javax.swing.GroupLayout painelMenu1Layout = new javax.swing.GroupLayout(painelMenu1);
        painelMenu1.setLayout(painelMenu1Layout);
        painelMenu1Layout.setHorizontalGroup(
            painelMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelMenu1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelProgresso2, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelBotao2, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(painelMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painelMenu1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(painelOpcoes3, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(20, Short.MAX_VALUE)))
        );
        painelMenu1Layout.setVerticalGroup(
            painelMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelMenu1Layout.createSequentialGroup()
                .addContainerGap(241, Short.MAX_VALUE)
                .addComponent(painelBotao2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(painelProgresso2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(painelMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painelMenu1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(painelOpcoes3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(247, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 662, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addComponent(painelMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(27, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 437, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(painelMenu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        painelMestre.addTab("Mesclagem", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(campoSaida)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(campoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelMestre, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(campoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(campoSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(painelMestre, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelMestre.getAccessibleContext().setAccessibleName("Conversor");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        campoEntrada.setText(WatsonController.getEntrada());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        campoSaida.setText(WatsonController.salvarArquivo());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnProcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessarActionPerformed
        if (campoEntrada.getText().isEmpty() || campoSaida.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "informe uma entrada e uma saída!");
        } else {
            WatsonController.converter();
        }
    }//GEN-LAST:event_btnProcessarActionPerformed

    private void botaoDesmembrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDesmembrarActionPerformed
        if (campoEntrada.getText().isEmpty() || campoSaida.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "informe uma entrada e uma saída!");
        } else {
            WatsonController.desmembrar();
        }
    }//GEN-LAST:event_botaoDesmembrarActionPerformed

    private void botaoCondensarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCondensarActionPerformed
        if (campoEntrada.getText().isEmpty() || campoSaida.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "informe uma entrada e uma saída!");
        } else {
            WatsonController.mesclar();
        }
    }//GEN-LAST:event_botaoCondensarActionPerformed

    private void chkRemoveLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkRemoveLinkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkRemoveLinkActionPerformed


    /**
     * @param args the command line arguments
     * @param block
     */
    public static void main(String args[], String block) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WatsonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WatsonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WatsonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WatsonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new WatsonGUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JProgressBar barraProgressoCond;
    public static javax.swing.JButton botaoCondensar;
    public static javax.swing.JButton botaoDesmembrar;
    public static javax.swing.JButton btnProcessar;
    private javax.swing.ButtonGroup buttonGroup;
    public static javax.swing.JTextField campoEntrada;
    public static javax.swing.JTextField campoSaida;
    public static javax.swing.JCheckBox chkAcent;
    public static javax.swing.JCheckBox chkAcent2;
    public static javax.swing.JCheckBox chkAcentCond;
    public static javax.swing.JCheckBox chkRT;
    public static javax.swing.JCheckBox chkRemoveLink;
    public static javax.swing.JCheckBox chkRemoveLink2;
    public static javax.swing.JCheckBox chkRemoveLinkCond;
    public static javax.swing.JCheckBox chkRemoveRT2;
    public static javax.swing.JCheckBox chkRemoveRTCond;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JPanel painelBotao;
    private javax.swing.JPanel painelBotao1;
    private javax.swing.JPanel painelBotao2;
    private javax.swing.JPanel painelInterno;
    private javax.swing.JPanel painelInternoDesm;
    private javax.swing.JPanel painelMenu;
    private javax.swing.JPanel painelMenu1;
    public static javax.swing.JTabbedPane painelMestre;
    private javax.swing.JPanel painelOpcoes;
    private javax.swing.JPanel painelOpcoes2;
    private javax.swing.JPanel painelOpcoes3;
    private javax.swing.JPanel painelProgresso;
    private javax.swing.JPanel painelProgresso1;
    private javax.swing.JPanel painelProgresso2;
    private javax.swing.JPanel painelSeparacao;
    public static javax.swing.JProgressBar progressDesm;
    public static javax.swing.JProgressBar progresso;
    public static javax.swing.JLabel qtdArquivos;
    public static javax.swing.JRadioButton rdbMultiplos;
    public static javax.swing.JRadioButton rdbUnico;
    // End of variables declaration//GEN-END:variables
}
